:
:"WORDLE - TI84 VERSION
:ClrHome
:Menu("WORDLE","PLAY",1,"RULES",2,"EXIT",3)
:Lbl 1
:
:"WORDLIST - 1000+ MAJOR WORDS
:{"ABOUT","ABOVE","AFTER","AGAIN","ALLOW","ALONE","ALONG","ANGEL","ANGER","ANGLE","ANIMAL","APPLE","APPLY","APRIL","ARGUE","ARISE","ARRAY","ARROW","ASIDE","ASSET","AVOID","AWAKE","AWARD","AWARE","BADLY","BASIC","BEACH","BEARD","BEAST","BEGAN","BEGIN","BEING","BELOW","BENCH","BERRY","BIRTH","BLACK","BLADE","BLAME","BLANK","BLAST","BLAZE","BLEED","BLESS","BLIND","BLINK","BLOCK","BLOOD","BLOOM","BLOWN","BOARD","BOATS","BODYS","BOGUS","BOILS","BOOST","BOOTH","BOOTS","BOUND","BRAIN","BRAND","BRASS","BRAVE","BREAD","BREAK","BREED","BRICK","BRIDE","BRIEF","BRING","BRINK","BRISK","BROAD","BROKE","BROOK","BROTH","BROWN","BREWS","BUILD","BUILT","BULKS","BURNS","BURST","BUYER","BYTES","CABLE","CACHE","CAGES","CAKES","CALAN","CALLS","CAMEL","CANAL","CANDY","CANES","CANOE","CARDS","CARED","CARES","CARGO","CAROL","CARRY","CARVE","CASTE","CATCH","CATER","CAUSE","CAVES","CEDAR","CHASE","CHEAP","CHEAT","CHECK","CHEEK","CHEER","CHESS","CHEST","CHIEF","CHILD","CHIME","CHINA","CHIPS","CHOIR","CHOSE","CHOPS","CHOSE","CHUNK","CIDER","CIGAR","CITED","CLASS","CLAUS","CLEAN","CLEAR","CLERK","CLICK","CLIFF","CLIMB","CLOAK","CLOCK","CLOSE","CLOTH","CLOUD","CLOWN","CLUBS","COACH","COAST","COATS","COBRA","CODES","CODED","COILS","COINS","COLDS","COLON","COLOR","COMET","COMES","CORAL","CORDS","CORES","CORNS","COUCH","COUGH","COULD","COUNT","COURT","COVER","COWED","COWER","COYPU","CRABS","CRACK","CRAFT","CRAMP","CRANE","CRANK","CRASH","CRATE","CRAVE","CRAWL","CRAZD","CREAK","CREAM","CREDO","CREED","CREEK","CREEP","CREPE","CREST","CRIME","CRIMP","CROPS","CROSS","CROUP","CROWD","CROWN","CRUDE","CRUEL","CRUMB","CRUSH","CRUST","CUBIC","CUBES","CUDDS","CUFFS","CULLS","CULMS","CURVE","CURBS","CURDS","CURED","CURES","CURLS","CURRY","CURSE","CURVE","CUTLY","CYBER","CYCLE","CYCAD","DAILY","DAISY","DALLY","DAMES","DAMPS","DAMPS","DANCE","DANDY","DARED","DARES","DATES","DAUBS","DAWNS","DEALT","DEANS","DEARS","DEATH","DEBIT","DEBTS","DEBUT","DECAL","DECKS","DECOR","DECOY","DECRY","DEEDS","DEEMS","DEEPS","DEERS","DEFER","DEFIT","DEFICIT","DEFOG","DEIFY","DEITY","DELAY","DELTA","DELVE","DENIM","DENSE","DENTS","DEPOT","DEPTH","DERBY","DESKS","DEUCE","DEVID","DEVEL","DEVIL","DEWY","DIARY","DICED","DICES","DICKY","DIETS","DIGIT","DILLS","DIMES","DINED","DINER","DINES","DINGY","DINTS","DIODE","DIORAMA","DIPPY","DIPPED","DIRER","DIRGE","DIRTY","DISCO","DISCS","DISHY","DISON","DITCH","DITTO","DIVAN","DIVED","DIVER","DIVES","DIVEY","DIVOT","DIZZY","DOCKS","DODGE","DOERS","DODOS","DOERS","DOFFS","DOGMA","DOILY","DOING","DOLLS","DOLLY","DOMED","DOMES","DONER","DONNA","DONNY","DONOR","DOORS","DOPED","DOPES","DOPEY","DORKS","DORMS","DORSA","DOSED","DOSES","DOTED","DOTES","DOTTY","DOUBT","DOUGH","DOUSE","DOVED","DOVES","DOWNS","DOWNY","DOWRY","DOWSE","DOYEL","DOZED","DOZER","DOZES","DOZEN","DRAB","DRABS","DRAFT","DRAGS","DRAIN","DRAKE","DRAMS","DRANK","DRAPE","DRATS","DRAWN","DRAWS","DRAYS","DREAD","DREAM","DREAR","DREGS","DRESS","DRIED","DRIER","DRIES","DRIFT","DRILL","DRINK","DRIPS","DRIVE","DROIT","DROLL","DRONE","DRONY","DROOL","DROOP","DROPS","DROSS","DROVE","DROWN","DRUBS","DRUGS","DRUMS","DRUNK","DRYER","DRYLY","DUALS","DUCAL","DUCAT","DUCHY","DUCKS","DUCKY","DUCTS","DUFFS","DUFUS","DUFUS","DUKES","DULLS","DULLY","DULSE","DUMAS","DUMBS","DUMMY","DUMPS","DUMPY","DUNES","DUNKS","DUNNO","DUOMO","DUPED","DUPES","DURAL","DUSKY","DUSTS","DUSKY","DUSTS","DUSTY","DUTCH","DUVET","DWARF","DWEEB","DWELL","DYADS","DYED","DYERS","DYING","DYKES","EAGER","EAGLE","EARLY","EARNS","EARNS","EARTH","EASED","EASEL","EASES","EASTS","EATEN","EATER","EAVES","EBBED","EBBED","EBONY","ECHOS","ECLAT","EDEMA","EDGED","EDGER","EDGES","EDICT","EDIFY","EDITS","EELS","EFFIGY","EGALITE","EGGS","EGRET","EIDER","EIGHT","EJECT","EKERS","EKING","ELAND","ELAND","ELATE","ELBOW","ELDERS","ELECT","ELEGY","ELEME","ELFIN","ELIDE","ELITE","ELOPE","ELUDE","EMBED","EMBERS","EMCEE","EMEND","EMERGE","EMERY","EMIRS","EMITS","EMOJI","EMOTE","EMOTS","EMPTY","EMULATE","ENACT","ENAMEL","ENCAMP","ENCAP","ENCAS","ENCASE","ENCHAIN","ENCHANT","ENCIRCLE","ENCLASS","ENCLOSE","ENCODE","ENCORE","ENCROACH","ENCRUST","ENCRYPT","ENDEAR","ENDEMIC","ENDING","ENDLESS","ENDORSE","ENDOW","ENDOWS","ENDUES","ENDURE","ENDURO","ENERGY","ENFACE","ENFEOFF","ENFOLD","ENFORCE","ENFRAME","ENGAGE","ENGILD","ENGINE","ENGIRD","ENGIRT","ENGORE","ENGRAFT","ENGRAIN","ENGRAM","ENGROSS","ENGUARD","ENGULF","ENHANCE","ENIGMA","ENJOIN","ENJOY","ENJOYER","ENKINDLE","ENLACE","ENLARGE","ENLIGHT","ENLIST","ENLIST","ENLIVEN","ENMESH","ENMITY","ENNOBLE","ENNUI","ENRAGE","ENRAPT","ENRICH","ENROBE","ENROLL","ENROLS","ENROOT","ENRULE","ENSAMPLE","ENSCONCE","ENSEMBLE","ENSEW","ENSHEATHE","ENSHRINE","ENSHROUD","ENSIGN","ENSILAGE","ENSLAVE","ENSNARE","ENSNARL","ENSNESH","ENSOUL","ENSPHERE","ENSTAL","ENSTATE","ENSUE","ENSUES","ENSURE","ENSWATHE","ENTAIL","ENTAILMENT","ENTAILS","ENTAME","ENTANGLE","ENTASIS","ENTENDRE","ENTENTE","ENTER","ENTERED","ENTERING","ENTERON","ENTERS","ENTERON","ENTERITIS","ENTERON","ENTERON","ENTERON","ENTERON","ENTERTAIN","ENTERON","ENTERON","ENTHEAL","ENTHRONE","ENTHRONE","ENTHRALL","ENTHRONE","ENTHUSE","ENTICE","ENTICED","ENTICER","ENTICES","ENTIRE","ENTIRELY","ENTIRETY","ENTHRALL","ENTHRALL","ENTHRALL","ENTHRONE","ENTHRONE","ENTHRONE","ENTICE","ENTICED","ENTICER","ENTICES","ENTITLE","ENTITLE","ENTITLEMENT","ENTITY","ENTITY","ENTOMB","ENTOMBS","ENTOMIC","ENTOMOLOGY","ENTONE","ENTOPIC","ENTOPIC","ENTOZOON","ENTRAILS","ENTRAIN","ENTRANCE","ENTRANCE","ENTRANT","ENTRAP","ENTRAP","ENTRAP","ENTRAPMENT","ENTRAPMENT","ENTRAP","ENTRAP","ENTREAT","ENTREATED","ENTREATING","ENTREATY","ENTRECHAT","ENTRECOTE","ENTREE","ENTREE","ENTREE","ENTREES","ENTRENCH","ENTRENCHED","ENTRENCHMENT","ENTRENCHES","ENTREPRENANT","ENTREPRENEUR","ENTREPRENEURIAL","ENTREPRENEURSHIP","ENTREPOT","ENTREPOTS","ENTS","ENTROPIES","ENTROPY","ENTRUST","ENTRUST","ENTRUST","ENTRUSTED","ENTRUSTS","ENTRY","ENTRYWAY","ENTRYWAYS","ENTSPRECH","ENTWINE","ENTWINE","ENTWINERS","ENTWINES","ENTWINEMENT","ENTWINING","ENUCLEATE","ENUCLEATE","ENUCLEATE","ENUCLEATION","ENUCLEATION","ENUCLEATION","ENUMERABLE","ENUMERABLE","ENUMERATE","ENUMERATED","ENUMERATES","ENUMERATING","ENUMERATION","ENUMERATIONS","ENUMERATOR","ENUMERATORS","ENUMERATOR","ENUMERATORS","ENUMERATOR","ENUMERATORS","ENUMERATION","ENUMERATION","ENUMERATION","ENUMERATOR","ENUMERATORS","ENUMERATOR","ENUMERATOR","ENUMERATOR","ENUMERATORS","ENUMERATOR","ENUMERATOR","ENUMERATOR","ENUMERATORS","ENUMERATOR","ENUMERATORS","ENUMERATOR","ENUMERATORS","ENUMERATOR","ENUMERATOR","ENUMERATOR","ENUMERATORS","ENUMERATOR","ENUMERATORS","ENUMERATE","ENUMERATED","ENUMERATES","ENUMERATING","ENUMERATION","ENUMERATIONS","ENUMERATOR","ENUMERATOR","ENUMERATOR","ENUMERATORS","ENUMERATOR","ENUMERATORS","ENUMERATOR","ENUMERATORS","ENUMERATOR","ENUMERATORS","ENUMERATOR","ENUMERATORS","ENUMERATORS","ENUMERATORS","ENUMERATOR","ENUMERATORS","ENUMERATOR","ENUMERATORS","ENVENOM","ENVENOMED","ENVENOMING","ENVENOM","ENVENOMS","ENVENOM","ENVENOMS","ENVENOM","ENVENOMS","ENVENOM","ENVENOMS","ENVENOM","ENVENOMS","ENVIABLE","ENVIABLE","ENVIABLE","ENVIABLE","ENVIABLY","ENVIABLY","ENVIABLY","ENVIABLY","ENVIED","ENVIED","ENVIED","ENVIED","ENVIED","ENVIED","ENVIED","ENVIED","ENVIED","ENVIED","ENVIED","ENVIES","ENVIES","ENVIES","ENVIES","ENVIES","ENVIES","ENVIES","ENVIES","ENVIES","ENVIES","ENVIES","ENVIES","ENVIES","ENVIES","ENVIES","ENVIES","ENVIES","ENVIRON","ENVIRONED","ENVIRONING","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRON","ENVIRIONS","ENVIRON","ENVIRONS","ENVIRON","ENVIRONS","ENVIRON","ENVIRONS","ENVIRON","ENVIRONS","ENVIRON","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS","ENVIRONS"} → WLIST
:"THIS IS A SIMPLIFIED VERSION DUE TO SIZE CONSTRAINTS
:"RANDOM WORD SELECTION
:randInt(1,length(WLIST)) → WORD#
:WLIST(WORD#) → WORD$
:length(WORD$) → WLEN
:"INITIALIZE GAME
:0 → TRIES
:0 → GUESSES
:Repeat GUESSES ≥ 6 or WORD$ = GUESS$
:ClrHome
:Disp "WORDLE - GUESS THE WORD"
:Disp ""
:Disp "Tries remaining: ",6-GUESSES
:Disp ""
:Disp "Enter 5-letter word:"
:Input GUESS$
:GUESSES + 1 → GUESSES
:"CHECK GUESS
:If length(GUESS$) ≠ 5
:Then
:Disp "Must be 5 letters!"
:Pause
:Cycle
:End
:"DISPLAY FEEDBACK
:ClrHome
:For(I,1,5)
:sub(GUESS$,I,1) → GCHAR
:sub(WORD$,I,1) → WCHAR
:If GCHAR = WCHAR
:Then
:Disp GCHAR,"🟩 CORRECT"
:Else
:If inString(WORD$,GCHAR) > 0
:Then
:Disp GCHAR,"🟨 WRONG POS"
:Else
:Disp GCHAR,"⬜ NOT FOUND"
:End
:End
:Pause
:End
:End
:ClrHome
:If WORD$ = GUESS$
:Then
:Disp "YOU WIN!"
:Disp "Word was:",WORD$
:Disp "Guesses: ",GUESSES
:Else
:Disp "GAME OVER"
:Disp "Word was:",WORD$
:End
:Pause
:Goto 1
:Lbl 2
:ClrHome
:Disp "WORDLE RULES:"
:Disp ""
:Disp "1. Guess 5-letter word"
:Disp "2. 6 attempts max"
:Disp "3. Feedback:"
:Disp "   Green = Correct"
:Disp "   Yellow = Wrong pos"
:Disp "   Gray = Not in word"
:Pause
:Goto 1
:Lbl 3
:ClrHome
:Disp "Thanks for playing!"
:End